### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by davidmoshal** [buildkite/cli#102]
Hi just tried to install bk cli on a new developer machine (Ubuntu 20.04), 
and ran into several issues, both using the binary from the releases page and also using Homebrew.

(1) With the binary from the releases page I get this error:
```sh
./bk-linux-amd64-1.1.0 
2021/01/04 18:44:19 Error getting git commit: exit status 128
2021/01/04 18:44:19 Error getting git branch: exit status 128
🚨 exec: "buildkite-agent": executable file not found in $PATH
```

It's asking for an agent, just checking because I don't see any docs on that topic, 
but does a non-build developer machine need to run the build agent in order to use the CLI ??

- if so, what's the best way to configure it such that it's only available for local builds, not part of the agent build pool for remotely triggered builds

(2) using Homebrew I get a different error:
```sh
# without sudo:
bk 
zsh: permission denied: bk

# with sudo:
sudo bk
sudo: bk: command not found
```
So first it says permission denied, then it says command not found (presumably that's not the bk command but some other command that it can't find?).

**Comment by mcncl** [comment]
👋 Thanks for raising the issue! We've shipped v3 which shouldn't have this issue; it doesn't have a `local run` command; as you've seen there are complexities around keeping it up to date. We're looking at alternatives to `local run` that may provide longevity and less maintenance.
