### ISSUE TITLE
stuck script on ubuntu 20.04 server 

### ISSUE THREAD

**Issue by KaushikSathvara** [buildkite/cli#103]
```
kaushik@ubuntu:~/project$ ./bk-linux-amd64-1.1.0 
>>> Starting local agent 🤖
>>> Starting build 👟
>>> Executing initial command: buildkite-agent pipeline upload
```
Any idea what's the issue? Also there is no steps included in documentation of installation of bk script.

**Comment by mcncl** [comment]
👋 Given the age of this issue and the number of versions release since, as well as the most recent rework in `3.x.x` I'm going to close this issue for now. Cheers!
