### ISSUE TITLE
Ability to choose individual step(s)

### ISSUE THREAD

**Issue by petemounce** [buildkite/cli#11]
We have a monorepo with a pre-merge pipeline that runs many disparate steps.

For local iteration it would be really convenient to run a subset of those steps.

Could `bk local run ..... --steps foo bar baz` become possible? Run the specified step(s) in the order given?

**Comment by lox** [comment]
The run command has a `--filter` flag that operates on the step labels:

`bk local run --filter '(foo|bar|baz)'`

It's not clear that filter is inclusive vs exclusive now that I look at it, perhaps `--include` and `--exclude` would be better, or `--match`? I'm less keen on the idea of specifying arbitrary orderings.

**Comment by petemounce** [comment]
I think since the steps are logically isolated from one another, ordering should not matter...? As in, BK-remote will run them in whatever order it happens to feel like. Perhaps BK-local should intentionally randomise the order to avoid any order-coupling? So, yeah, reject my run-in-particular-order suggestion, that's clearly bogus now I've thought about it.

I like `--include` and `--exclude`, personally; they imply maybe-plural matches. Needs to be clear which takes preference, though.

**Comment by lox** [comment]
@petemounce steps aren't logically isolated, they depend on things happening before them! It's a pipeline, so things like meta-data and artifacts might be processed incrementally. 

My issue with `--include` and `--exclude` is that you need to read the docs to figure out how it works. I'll think it over, but for now, `--filter` will get you started!

**Comment by petemounce** [comment]
Oh, point, yes; hadn't been thinking about wait and block. Most of ours in a mono repo are simply to run everything. Only recently are there waits and blocks.

**Comment by lox** [comment]
I might close this one for now, as I think `--filter` should cover it.
