### ISSUE TITLE
[feature request] Create pipeline

### ISSUE THREAD

**Issue by jtomaszewski** [buildkite/cli#111]
Hey guys,

we have a bunch of repositories that now we have to migrate from our previous CI to buildkite, and having an ability to create a bk pipeline using CLI would be quite helpful. Is that something you plan to do at some point?

**Comment by mcncl** [comment]
Pipelines can be created in v3 of the CLI, recently released 🙂 https://github.com/buildkite/cli/releases/tag/v3.0.0
