### ISSUE TITLE
bk run fails with opaque error

### ISSUE THREAD

**Issue by nrdxp** [buildkite/cli#112]
```console
❯ bk run
>>> Starting local agent 🤖
>>> Starting build 👟
>>> Executing initial command: buildkite-agent pipeline upload
🚨 Initial command failed: Job failed with code 1
```
Why is it trying to upload anything? I just want it to run locally. Trying a minimal yml doesn't seem to help anything:
```yaml
steps:
  - command: "echo foo"
```

**Comment by childish-sambino** [comment]
Seeing the same thing with `bk local run`. Any suggestions?

**Comment by lukoktonos** [comment]
I saw this and the issue for me was that I ran `brew install bk` instead of the correct `brew install buildkite/cli/bk`. The latter no longer produced the error.

**Comment by mcncl** [comment]
The `local run` isn't in 3.0.0 and we don't currently have a view to add it in; as has been seen, keeping it in line with the ongoing changes in the agent can mean it falls out of sync. We'll be looking at alternative approaches to using `local run`.
