### ISSUE TITLE
Implement pipeline upload --replace

### ISSUE THREAD

**Issue by GMNGeoffrey** [buildkite/cli#122]
When running `buildkite-agent pipeline upload --replace` right now, you just get `panic: Replace not implemented`. Taking a look at the [code](https://github.com/buildkite/cli/blob/07dc32aff6519043c3a786011e394e5c04356029/local/run.go#L538) this looks pretty trivial to implement. It would be exactly like prepend except without including the existing steps. Is there something I'm missing here? I guess that wouldn't account for the caveat that replace will not replace already-running steps, but AFAICT the steps are being run sequentially, so a later step should never be running anyway.

**Comment by mcncl** [comment]
We've shipped v3 which currently doesn't have a `local run` tool; as you've seen there are complexities around keeping it up to date. We're looking at alternatives to `local run` that may provide longevity and less maintenance.
