### ISSUE TITLE
Failure parsing group steps

### ISSUE THREAD

**Issue by GMNGeoffrey** [buildkite/cli#123]
It seems there is not support for group steps. If I try to run a pipeline with a group step locally, I get an error like it's trying to interpret it as a command step.

> 🚨 Error: The command phase has no `command` to execute. Provide a `command` field in your step configuration, or define a `command` hook in a step plug-in, your repository `.buildkite/hooks`, or agent `hooks-path`.

Here's a minimal reproduction

```shell
bk run <(cat <<EOF
steps:
  - group: "Some group"
    steps:
      - label: "Hello"
        commands: "echo hello"
      - label: "World"
        commands: "echo world"
EOF
)
```

**Comment by tylerauerbeck** [comment]
👍🏻 +1 Can confirm I'm seeing this locally as well.

**Comment by gorbak25** [comment]
Also affects me :( Any workarounds for now?

**Comment by mcncl** [comment]
The `local run` isn't in 3.0.0 and we don't currently have a view to add it in; as has been seen, keeping it in line with the ongoing changes in the agent can mean it falls out of sync. We'll be looking at alternative approaches to using `local run`.
