### ISSUE TITLE
Export emoji package

### ISSUE THREAD

**Issue by kevinburke** [buildkite/cli#126]
I would love to use the emoji package in my own Buildkite client, but it's not exported. Would it be possible to export the functions that make it possible to translate e.g. `:pipeline:` into emojis?

**Comment by kevinburke** [comment]
Here's my basic attempt at this: https://github.com/kevinburke/buildkite/commit/72abf9c23d7bbdc999a964f55644dac1fc45eb28

I'm using iTerm2, and I can see base64 data being downloaded and printed, but iTerm2 can't render it - I just get one half of a broken image in the terminal. Any idea what I'm doing wrong?

<img width="724" alt="kevinburke@NVG6NNXHPK:~:src:github com:kevinburke:" src="https://user-images.githubusercontent.com/234019/175468246-cdd25675-68fa-4822-80f3-0724ddc1696e.png">

**Comment by kevinburke** [comment]
Ah... this is another master vs. main issue. I think it's working now, once I fix that!

**Comment by mcncl** [comment]
We are looking at releasing the emoji package as its own thing, so this will likely be done in the future but not as a part of the CLI.
