### ISSUE TITLE
Is it possible to run a pipeline locally in a clear directory?

### ISSUE THREAD

**Issue by gorbak25** [buildkite/cli#143]
I would like to run the local pipelines in a clear directory while respecting .gitignore, currently the steps run in the current directory. For ex I have a step which requires that there are no node_modules present then the step will fail while running locally.

**Comment by mcncl** [comment]
The `local run` isn't in 3.0.0 and we don't currently have a view to add it in; as has been seen, keeping it in line with the ongoing changes in the agent can mean it falls out of sync. We'll be looking at alternative approaches to using `local run`.
