### ISSUE TITLE
Unintuitive error message from CLI when IP restriction is enforced

### ISSUE THREAD

**Issue by saviogl** [buildkite/cli#145]
When IP restriction is enforced, cli requests returns a pretty unintuitive message, without the authentication context

See the attachment below: 

<img width="283" alt="image" src="https://user-images.githubusercontent.com/8523281/234663229-ac47599e-afab-436d-b149-fe9345c57cc4.png">

Running the same command with `--debug-graphql` we get additional information and context as to why the request failed, but it would be great to have a better error management strategy to improve the UX of the cli tool.

**Comment by mcncl** [comment]
Thanks for raising this, @saviogl. We don't have a `--debug-graphql` flag in `v3`, so perhaps we need to look in to supporting debugging upstream errors and then how we would produce an IP restriction error.

**Comment by mcncl** [comment]
When no build is created we now output an error instead of a blank URL for the created build, https://github.com/buildkite/cli/commit/67f68cb99b5542853c2b7dfdb5a547bbc2d522a9. 

We can look in to more verbose erroring in the future, but it's not planned for now.
