### ISSUE TITLE
Feature: build step logs tailing

### ISSUE THREAD

**Issue by viraptor** [buildkite/cli#146]
I'd love to be able to tail a specific step of the build in my terminal.

I imagine it would work with something like:
```
bk build create ...
# get the build id

bk build log (build id) "Step name"
# downloads the output

bk build tail (build id) "Step name"
# follows output of a running step
```

**Comment by mcncl** [comment]
@viraptor 👋  with the release of `3.x.x` I'm taking a look through issues opened to see what we might be able to add; there isn't really a way for us to do this given logs don't stream to an API endpoint, so we'd either need to print job logs as a job finished, which isn't a stream you can then "`tail`". We have added in the `bk build watch` command which will kind of `tail` to the terminal as job states change/update and will update the build state too. Let us know if that covers your needs, given log streaming isn't really an option, at least in a _live_ sense.
