### ISSUE TITLE
bk build create fails on graphql complexity

### ISSUE THREAD

**Issue by sj26** [buildkite/cli#155]
I can't use bk to create builds:

```
$ bk build create
🚨 GraphQL error: Query has complexity of 501503, which exceeds max complexity of 50000
```

Any idea what's going on?

(I want to create a bunch of builds to stress test a pipeline.)

**Comment by jradtilbrook** [comment]
@sj26 if no pipeline flag is passed to the command, the CLI attempts to look up all pipelines and match it to the current directory. That looks like whats happening here. We are working on improving this in some fashion, but for now passing `--pipeline <slug>` to the command should fix this for you.

Depending how many builds you want to start, you might still hit a rate limit though
