### ISSUE TITLE
Adjust GraphQL query complexity threshold or improve query efficiency

### ISSUE THREAD

**Issue by dimo414** [buildkite/cli#162]
Trying out the CLI for the first time and hitting this error:

```
$ ~/bin/buildkite pipeline list 
🚨 GraphQL error: Query has complexity of 501503, which exceeds max complexity of 50000

$ ~/bin/buildkite pipeline list --limit=5
🚨 GraphQL error: Query has complexity of 501503, which exceeds max complexity of 50000
```

I see a mention of the same complexity score 501503 in #155, which makes me think this is an issue with the CLI itself (vs. the size of my pipelines or something else specific to me). Trying with `--debug-graphql` reports this is the offending query:

```
{
  "query": "query {\n\t\t\tviewer {\n\t\t\t  organizations {\n\t\t\t\tedges {\n\t\t\t\t  node {\n\t\t\t\t\tslug\n\t\t\t\t\tpipelines(first:500) {\n\t\t\t\t\t  edges {\n\t\t\t\t\t\tnode {\n\t\t\t\t\t\t\tid\n\t\t\t\t\t\t\tslug\n\t\t\t\t\t\t\turl\n\t\t\t\t\t\t\trepository {\n\t\t\t\t\t\t\t\turl\n\t\t\t\t\t\t\t }\n\t\t\t\t\t\t}\n\t\t\t\t\t  }\n\t\t\t\t\t}\n\t\t\t\t  }\n\t\t\t\t}\n\t\t\t  }\n\t\t\t}\n\t\t  }",
  "variables": null
}
```

The suggestion in the linked bug and in #160 is to constrain the search to a specific pipeline, but there's no such option on `pipeline list`, and neither `--limit` nor `--fuzzy` appear to reduce the query complexity.

It seems like the CLI is effectively broken unless this query is improved or the server is adjusted to permit it.

**Comment by guhou** [comment]
I see the same error, so unless it's an enormous coincidence the complexity is inherent to the query rather than anything to do with my pipeline configuration. This CLI is kinda useless as it is. 😞 

```
$ bk pipeline list --limit 1
🚨 GraphQL error: Query has complexity of 501503, which exceeds max complexity of 50000
```

**Comment by jradtilbrook** [comment]
Thanks for letting us know of these problems 👍 We are working on a complete revamp of the CLI and will tackle this problem with the new version

**Comment by dimo414** [comment]
Is there really no workaround that could be landed in the current CLI in the meantime? The existing CLI is unusable, and it's been like this for months.
