### ISSUE TITLE
iTerm2 warns about "Allow Terminal-Initiated Display?"

### ISSUE THREAD

**Issue by torarnv** [buildkite/cli#168]
When running `bk` (2.0) in a repo with a simple pipeline I get:

"The terminal has initiated display of a file named “Unnamed file” of size 0 bytes. Allow it?"

<img width="278" alt="image" src="https://github.com/buildkite/cli/assets/7536/b9aee988-b144-4a45-be21-c52310717007">

**Comment by jradtilbrook** [comment]
Hey @torarnv that seems to be part of iterm2 (https://gitlab.com/gnachman/iterm2/-/issues/8771). Since the bk cli will output to stdout. It's a security feature of the terminal, I don't believe we can change anything about that as its expected that the CLI output to stdout

**Comment by torarnv** [comment]
Thanks @jradtilbrook. 

I don't have this issue for any other tools I run though, and they all echo to stdout as well (even a simple `echo foo` will, unless piped somewhere) 😄 

Can you elaborate on what `bk` does that would be different in this case? Why does iTerm reference an "Unnamed file" of size 0?

**Comment by jradtilbrook** [comment]
Good point 👍  Can you give us the full command you ran (and possibly your .buildkite/pipeline.yml) if it applies. And we can look into it soon

**Comment by torarnv** [comment]
The issue seems to be triggered by using `:macos:` in the label:

```pipeline.yml
steps:
  - label: ":macos: <---"
    command: echo hello
```
And we end up hitting this https://github.com/gnachman/iTerm2/blob/master/sources/PTYSession.m#L14381

<img width="788" alt="image" src="https://github.com/buildkite/cli/assets/7536/41013403-e94c-4110-9b12-f0c9ffe63909">

**Comment by torarnv** [comment]
@jradtilbrook were you able to reproduce?

**Comment by jradtilbrook** [comment]
Hi @torarnv no I haven't looked into this. Just to manage your expectations, I don't think we will get to this. Our efforts are focussed on a brand new implementation of the BK CLI.

It looks like it would go away if you "allow" and remember. If that works, we will leave that as the workaround for now to allow us to continue with our other priorities
