### ISSUE TITLE
Output from a specific build and step

### ISSUE THREAD

**Issue by cycomachead** [buildkite/cli#18]
Somewhat related to #11

In my case, I've got a Rails app (with Docker) and develop locally (also with Docker). Sometimes I build something and CI fails way more than excepted. 😰 

What I'd love to be able to do is to locally grab just the output of the failures for one step of our builds. From there I could pass this to RSpec's `--only-failures` option and easily iterate on anything broken.

**Comment by mcncl** [comment]
Hmm, this is kind of supported in v3 with `build download`, where you can get the logs for the build.
