### ISSUE TITLE
Stalls on pipeline upload when used inside Docker container

### ISSUE THREAD

**Issue by toolmantim** [buildkite/cli#19]
I tried using this from a custom GitHub Action, but it seemed to stall. I tried running the same thing locally, and I have the same problem — it just stalls on the pipeline upload:

```
$ docker run -it --rm -v "$(PWD):/app" bk run local
>>> Starting local agent 🤖
>>> Starting build 👟
>>> Executing initial command: buildkite-agent pipeline upload
^C
>>> Gracefully shutting down...
🚨 Initial command failed: context canceled
```

The Dockerfile I'm using is here:
https://gist.github.com/toolmantim/c731730b4b4b7989f8f045956346bcfe

Any hints on how I'd be able to debug?

**Comment by lox** [comment]
When I run it with `--debug`, I see:

> 2019-02-04 23:34:30 FATAL  Missing build-path. See: `buildkite-agent start --help`

**Comment by toolmantim** [comment]
Oh, `--debug`! I didn't think of doing that. Thank you!!
