### ISSUE TITLE
GitHub scopes too large?

### ISSUE THREAD

**Issue by toolmantim** [buildkite/cli#2]
Is all we need a list of repos? There's a new GitHub App permissions scope that can give you that, without all this:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/153/41209032-df15368a-6d6b-11e8-819c-a32c7ee43ed3.png">

If we are asking for a god token, perhaps we need to spell out why a little more?

Also perhaps we need to say that the GitHub authorisation is only valid to your cli, and can't be used outside of the cli (if we were, say, to update the GitHub App settings or something). Assuming that's correct? I was only a little more comfortable once I noticed the `127.0.0.1` redirect at the bottom of the authorise screen.

**Comment by lox** [comment]
We need to write GitHub Webhooks, which unfortunately means we need to ask for all these things.
