### ISSUE TITLE
Allow supplying pipeline argument positionally

### ISSUE THREAD

**Issue by patrobinson** [buildkite/cli#264]
```
Usage:
  bk build view <number> [pipeline] [flags]
```

I should be able to supply `pipeline` without having to supply the `number` argument.

**Comment by mcncl** [comment]
@patrobinson just going through open issues and wanted to check in on this one; we support `bk build view -p PIPELINE_SLUG`. Does that solve this or would you want to _not_ have to use a `-p` flag?

**Comment by mcncl** [comment]
I'm going to close this out as done given there is an option to pass in just the pipeline with `-p`. You're welcome to reopen this if you feel it doesn't solve the initial issue. 🙂
