### ISSUE TITLE
Pass environment variables when creating a build

### ISSUE THREAD

**Issue by orien** [buildkite/cli#29]
I notice the '[Create a build](https://buildkite.com/docs/apis/rest-api/builds#create-a-build)' REST API call includes the capability to set environment variables.

It would be awesome if this CLI app exposed this feature so we could pass environments variables to builds from the command line.

**Comment by lox** [comment]
Sounds like a great idea!

**Comment by nikskiz** [comment]
I second that. Makes it helpful being able to build a pipeline which is expecting env vars.

**Comment by leighst** [comment]
Just need a shipit on this puppy! 

https://github.com/buildkite/cli/pull/61

**Comment by lox** [comment]
Done, thanks for the reminder @leighst

**Comment by leighst** [comment]
When do y'all think you might be able to release @lox ?

**Comment by orien** [comment]
I see this has been released in [version 1.0.0](https://github.com/buildkite/cli/releases/tag/v1.0.0).
