### ISSUE TITLE
Unable to configure on WSL

### ISSUE THREAD

**Issue by adamstrawson** [buildkite/cli#31]
I'm running Linux Subsystem on Windows, and when running `bk configure`, I get the below error, since WLS isn't able to open a browser. Is it possible to output the URL so that I can copy and paste into the browser. (Similar behaviour to how composer handles this.)

```
We need to authorize this app to access your repositories. This authorization is stored securely locally, buildkite.com never gets access to it.

When you press enter, your default browser will open and authenticate to github.com
❌

🚨 Github OAuth error: exec: "xdg-open": executable file not found in $PATH```
```

Running `0.3.0`

**Comment by lox** [comment]
We'll see what we can do!

**Comment by AdamsNimbus** [comment]
Successfully working on WSL with - https://github.com/4U6U57/wsl-open
