### ISSUE TITLE
Ability to run pipelines locally without giving out org's agent token?

### ISSUE THREAD

**Issue by rmtobin** [buildkite/cli#32]
Hey! 
We have a handful of folks within our org who would like to use the local pipeline running functionality of this, however they need to be running an instance of the agent, which requires our agent token. I'm hesitant to give out our org's agent token to every developer who wants to do local testing, given that it allows registration of new agents, which may unintentionally cause issues. Is there any way to get the local pipeline functionality without giving out our agent token? 

I tried using a fake token to see if it would still work, but unfortunately it appears to error out if the token is invalid.

**Comment by lox** [comment]
Glad to hear folks are interested! The idea was to be able to run locally without needing a token, so it sounds like there might be a bug somewhere. Where are you seeing an error about a token?

**Comment by rmtobin** [comment]
This is specifically for the `bk local run` command, which (unless I'm misunderstanding), requires the agent to be running locally, which does not run without a valid token. Attempting to run it without a token returns:  `FATAL  Missing token. See: `buildkite-agent start --help``

**Comment by lox** [comment]
Hmmm 🤔 the `bk local run` command should start up an agent and simulated buildkite agent API, I wonder why you are seeing that error. Could I trouble you for the exact `bk local run --debug` output?

**Comment by GaryPWhite** [comment]
I'll open this up again! I'm running something like: `buildkite-agent start --token="fake-token"` and seeing a failure to start with the trace:

```
2019-04-05 13:23:11 INFO   Registering agent with Buildkite...
2019-04-05 13:23:11 WARN   Buildkite rejected the registration (POST https://agent.buildkite.com/v3/register: 401 The token you provided "fake-token" is not a valid organization agent registration token.)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1a24e56]

goroutine 1 [running]:
github.com/buildkite/agent/agent.Register(0x202e260, 0xc0000a1cc0, 0xc0002b2000, 0xc00027c026, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/buildkite/agent/agent/register.go:61 +0x356
github.com/buildkite/agent/clicommand.glob..func1(0xc0000f49a0)
	/go/src/github.com/buildkite/agent/clicommand/agent_start.go:555 +0xbd6
github.com/buildkite/agent/vendor/github.com/urfave/cli.HandleAction(0x1b890c0, 0x1e828b8, 0xc0000f49a0, 0x0, 0xc000264000)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:503 +0x7c
github.com/buildkite/agent/vendor/github.com/urfave/cli.Command.Run(0x1e45e59, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1e57722, 0x18, 0x0, ...)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/command.go:165 +0x487
github.com/buildkite/agent/vendor/github.com/urfave/cli.(*App).Run(0xc0001e61c0, 0xc0000aa000, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/buildkite/agent/vendor/github.com/urfave/cli/app.go:259 +0x6e3
main.main()
	/go/src/github.com/buildkite/agent/main.go:109 +0x500
```

**Comment by rmtobin** [comment]
Sorry it's taken me so long to reply to this, but it was a matter of order. I had thought I needed to start the agent up first locally (which requires a token), then run `bk local run` in order to run a pipeline locally. 

However this works as expected if I just install the agent, don't start it up, and run `bk local run`. No token is needed. :)
