### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by jmikedupont2** [buildkite/cli#330]
I am looking to run the buildkite builds locally, also trying to figure out how to install this tool.
can you please provide better instructions, what version of go is supported?

I built it with 1.20.2 according to the instructions

this says to use run https://buildkite.com/changelog/44-run-pipelines-locally-with-bk-cli

go run cmd/bk/main.go run
```
internal/pipeline/resolver/picker.go:4:2: package slices is not in GOROOT (/gnu/store/7dijp9sg4gick93hphmb9p44ai2l0w8c-go-1.20.2/lib/go/src/slices)
note: imported by a module that requires go 1.2
```

also the release version does not have "run" command
I installed the latest release 3.0.0-beta.20240712 but it has no run command.
see 
https://forum.buildkite.community/t/installation-woes/3841

**Comment by jradtilbrook** [comment]
Thanks @jmikedupont2
The `run` functionality is in v2, but that changelog points to v0.3.0. You should be able to download the latest stable release from https://github.com/buildkite/cli/releases/tag/v2.0.0

We are working on v3 which doesn't have the `run` functionality ported over just yet.
