### ISSUE TITLE
Inferred file keyring backend can't easily be overridden

### ISSUE THREAD

**Issue by lachlancooper** [buildkite/cli#37]
On macOS I'm trying to use the `keychain` backend, but `file` is always the one chosen even when I explicitly specify `--keyring-backend=keychain`.

This seems to have been introduced in https://github.com/buildkite/cli/commit/3e9370c4c17e689837145651930d386d81233567. Following that change, inferring the `file` backend from `keyringFileDir` is no longer valid because the latter string now defaults to non-empty.

As confirmation of this behaviour, I'm able to work around the problem and use `keychain` by specifying `--keyring-file-dir ""`.

I think the solution is to only try to infer a backend if it's not explicitly specified. The inference of `file` from `keyringFileDir` will also need rethinking.

**Comment by lox** [comment]
Sorry about this! We fixed this in #51 I believe!
