### ISSUE TITLE
BK Init Command Fails When Not Admin-Level User

### ISSUE THREAD

**Issue by taliarhodes** [buildkite/cli#41]
In trying to initialize a new pipeline on Buildkite, I was attempting to run the `bk init` command.
Nothing had been setup in BuildKite at this stage.
When I ran the command at a user level (just part of the default "Everyone" team), the command failed with:
`"Checking for buildkite pipeline: GraphQL error: Please ensure at least one team is added to this pipeline"`
When running as an admin-level user, the init succeeded and I noticed when going to the web ui no team was assigned.
So it seems two things are happening:
1. A non-admin user doesn't have the ability to create a pipeline without a team assignment. (whether anyone of any level is supposed to be able to do this I do not know)
2. There doesn't appear to be any flag to provide a team for the CLI and thus it just fails with the above error.

Also, just to note: a user just part of the default everyone group, is able to select a team and successfully make a pipeline in the web ui, so I don't believe it's some sort of permissions issue. Though maybe there is some permission we can provide users so they can...not pass a team?

**Comment by mcncl** [comment]
This, I'd imagine, is now no longer an issue with the release of v3. Closing as done 🙂
