### ISSUE TITLE
Run bk configure in browserless environment

### ISSUE THREAD

**Issue by AnthonyWC** [buildkite/cli#42]
Currently one of the step for `bk configure` requires configuration of github cred within a browser:
```
──── Let's configure your github.com credentials 💻

We need to authorize this app to access your repositories. This authorization is stored securely locally, buildkite.com never gets access to it.

When you press enter, your default browser will open and authenticate to github.com
```

How to do this step in the command line in a browserless/headless environment?

**Comment by lox** [comment]
Good question! We hadn't considered that use-case yet, can you tell us a bit more about what you are using `bk` for in a browserless/headless environment?

**Comment by AnthonyWC** [comment]
Mainly for testing; imagine in environment where developers won't have direct ssh access to the buildkite agent but wanted to run bk in an test agent that they set up themselves.  With bksr this was easy enough to do w/ token authentication.

**Comment by toolmantim** [comment]
Are you wanting to use bk’s GitHub functionality in that case @AnthonyWC?

**Comment by AnthonyWC** [comment]
Actually the bksr functionality works fine; but I wanted to setup new pipeline directly from cli.  I think I need to authenticate first before I can do that and ran into issues in this headless environment.  I suppose I can try this in my laptop and see if that works as well.

**Comment by lukedirtwalker** [comment]
> Good question! We hadn't considered that use-case yet, can you tell us a bit more about what you are using bk for in a browserless/headless environment?

In a COVID world I have a simple answer to this. I have my workstation in the office and work on it remotely from my home computer. It would be great if such a setup would be supported.

**Comment by mcncl** [comment]
GH credentials are no longer required, so closing this for now.
