### ISSUE TITLE
Failed to find organization id for slug

### ISSUE THREAD

**Issue by AnthonyWC** [buildkite/cli#43]
After authentication; bk init process failed at this step:

```
Checking for pipeline file: .buildkite/pipeline.yml ✅
Checking for git repository and remote: https://github.com/XXXXX/XXXX ✅
Enter passphrase to unlock /Users/antho/.buildkite/keyring/:
Checking for buildkite pipeline: Failed to find organization id for slug "XXXXX" ❌
```

**Comment by dasevilla** [comment]
When I ran into this, the problem was that the GitHub org slug is different than the BuildKite org slug. I worked around it by specifying the `--pipeline` parameter with my BuildKite slug.
