### ISSUE TITLE
Enable retrying failed job based on BUILDKITE_JOB_ID

### ISSUE THREAD

**Issue by irlevesque** [buildkite/cli#47]
It would be very useful to be able to retry a failed job locally via `bk` by referencing the `BUILDKITE_JOB_ID`. I'd imagine `bk` fetching the job details from the API and starting a local build with the same environment variables, etc.

**Comment by mcncl** [comment]
The `local` command isn't available in v3 right now, so I'm going to close this issue out. We do plan on having some form of `local` runner, but what that looks like remains to be seen.

We don't plan on adding anything new to v2, however we may look to implement a `retry` option in the `job` command in v3.

**Comment by mcncl** [comment]
FWIW, we've just merged in a PR to support `bk job retry <UUID>` in v3
