### ISSUE TITLE
`bk init` parameters

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite/cli#48]
It would be ideal to be able to provide either a config file (yml, toml, or other)  to the `bk init` command to configure the pipeline from the CLI, or even better a `bk pipeline config` or similar command to do so.
That way we can create a "standard" pipeline config and easily bootstrap a bunch of repos. eg: GH settings, skip settings, etc.

**Comment by lox** [comment]
Cool idea @pecigonzalo!

**Comment by mcncl** [comment]
v3.0.0, released today, has a `bk init` command which will set up a boilerplate pipeline config which can be edited 🙂

**Comment by pecigonzalo** [comment]
Nice! I'll take a look. Seems to be closed as done instead of not planned right?
