### ISSUE TITLE
agent env variables

### ISSUE THREAD

**Issue by rborn** [buildkite/cli#54]
Hi,

I'm sorry if I'm not posting in the right place but I don't seem to be able to figure out how to do this:

I am using Buildkite on OsX to build ReactNative apps. All good and I'm very happy but I have the case where I need to pass some environment variables to the agent that are not the same with the machine I'm working on.

For example `ANDROID_HOME`

Setting this in the pipeline file is not an option as I want to be able to build the code without the need of extra changes and I don't know how to pass to the agent the variables already existent to a "normal" user.

Thanks for any help you could give 🤗

**Comment by lox** [comment]
Hi! 👋🏻 This is the issue tracker for the `bk` cli command, mind dropping us an email to hello@buildkite.com and we will assist?
