### ISSUE TITLE
[REQUEST] Support `DOCKER_HOST` etc

### ISSUE THREAD

**Issue by bjeanes** [buildkite/cli#55]
Because of crippling performance issues with Docker on macOS Mojave, I use [dinghy](https://github.com/codekitchen/dinghy) to run Docker on macOS, which essentially runs it in a VM then mounts local directories over NFS into the VM. It's hacky, but it is about a 10x performance improvement in IO-heavy projects :(.

I'm not sure if there are inherent limitations that would make this impossible, but it'd be great if I could use `bk` in this context. Currently, I get the following `bk local run` error: 

```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```

**Comment by mcncl** [comment]
👋 Thanks for raising the issue! We've shipped v3 which currently doesn't have a `local run` tool; as you've seen there are complexities around keeping it up to date. We're looking at alternatives to `local run` that may provide longevity and less maintenance.
