### ISSUE TITLE
GitHub Enterprise Support?

### ISSUE THREAD

**Issue by bresmith-wayfair** [buildkite/cli#60]
currently `bk` seems to point only at github.com...   any chance there will be support for GitHub Enterprise and on-prem installations? 

Thanks!

**Comment by lox** [comment]
I think that should be relatively easy, if y'all will use it, we're happy to make it work.

**Comment by agates4** [comment]
yes I will use it, I installed CLI and came here to report this issue before finding it is a duplicate

Wayfair would use this

**Comment by lporras** [comment]
Waiting for this feature too!

**Comment by amukherjeetwilio** [comment]
Also would be interested in this feature

**Comment by lox** [comment]
We're a bit behind in development on the `cli`, hoping to give it some attention soon. Thanks for your patience folks.

**Comment by kosmodromov** [comment]
Voice from 2021 - any news? :)

**Comment by nikwek** [comment]
> Voice from 2021 - any news? :)

Hi @kosmodromov - I'm late to the thread... what are you looking for? We support GitHub Enterprise but it looks like this is a request for the CLI to support GitHub Enterprise? I'm curious about your use case... Want to ping me at success@buildkite.com?

**Comment by Oded-B** [comment]
Hi @nikwek,
I've just ran in to this also, when trying to run `bk init` to setup webhooks in a new GH Enterprise repo

**Comment by mcncl** [comment]
👋 We've recently released `3.x.x` and the `init` command is a bit different to the previous one; it doesn't include an API call to create webhooks, for example. We may look at doing that in the future, however.
