### ISSUE TITLE
bk build create exit status 128 on osx

### ISSUE THREAD

**Issue by thirtytwobits** [buildkite/cli#63]
I'm unable to successfully create a build on osx High Sierra. I've tried using both the keyring and a file backend but I don't have enough documentation and the error messages are too opaque to know what I'm doing wrong. Please help:

```
> bk configure
──── Ok! Let's get started with configuring bk 🚀


──── Configuring Buildkite GraphQL credentials

Create a GraphQL token at https://buildkite.com/user/api-access-tokens/new. Make sure to tick the GraphQL scope at the bottom.

GraphQL Token:  [redacted] ✅

Securely stored GraphQL token! 💪
Wrote configuration to /Users/[redacted]/.buildkite/config.json 📝

For now, we will assume you are using GitHub. Support for others is coming soon! 😓

──── Let's configure your github.com credentials 💻

We need to authorize this app to access your repositories. This authorization is stored securely locally, buildkite.com never gets access to it.

When you press enter, your default browser will open and authenticate to github.com

Authenticated as [redacted] ✅
Securely stored GitHub token! 💪

Ok, you are good to go!
```
^^ This seems to work and I've also tried the following commands using both the osx keychain and a file keychain so I don't think this is the issue.

```
> bk init
Checking for pipeline file: .buildkite/pipeline.yml ✅
Checking for git repository and remote: exit status 128 ❌
🚨 exit status 128
```
```
> git status
On branch uavcan-v1/issues/235
nothing to commit, working tree clean
```
As  you can see, this is a fully functional repository that I use to submit to github all the time.
```
> bk build create --debug --debug-graphql
2019/07/27 11:05:04 [keyring] Considering backends: [keychain pass file]
2019/07/27 11:05:04 [keyring] Querying keychain for service="buildkite", account="graphql-token", keychain=""
2019/07/27 11:05:04 [keyring] Found item "Buildkite GraphQL Token"
🚨 exit status 128
```
Again, no useful debug information here, just "exit status 128".

Other commands:
```
> bk browse
🚨 exit status 128
> bk pipeline list
uavcan/libuavcan-v1
> bk local run
(this works)
```

I'd really like the ability to initiate a build from local changes! Thanks for helping (You all are rockstars🎸 by the way).

**Comment by keithpitt** [comment]
Thanks for the report @thirtytwobits! @lox any ideas?

**Comment by thirtytwobits** [comment]
This would be a huge win for us. Please let me know if I can provide more information.

**Comment by lox** [comment]
Sorry for the delay, will try and have a look today!

**Comment by lox** [comment]
This is very perplexing. Could you try this for me in the repo?

```bash
git remote get-url origin
```

Failing that, I might need to add some debugging output somewhere in there. Any chance you'd be able to collaborate with me on running it via source?

**Comment by thirtytwobits** [comment]
Oh ho! Figured it out. You have an unwritten requirement that the remote be called 'origin'. I don't use that convention (I use 'upstream' for the open-source repo and 'downstream' for my working repo). When I changed the remote name it all started working. Okay, now I can start playing around with this API to see if it does what our team needs. This github issue should be renamed:

**Provide better error messaging in bk.**

I can close this issue if you want a clean history or I can just edit the name. Which would you prefer?

Thanks again!
