### ISSUE TITLE
Pipeline can be found by fuzzy search but cannot browse to that pipeline

### ISSUE THREAD

**Issue by bangn** [buildkite/cli#65]
Hi there,

Thank you very much for implementing buildkite cli.

Currently, I got an issue running `bk browse`.
The pipeline can be found by running

```
bk pipline list --fuzzy=pipeline-name
```

However, when im in `pipeline-name` directory and run

```
bk browse
```

It outputs an error

```
🚨 Pipeline doesn't exist
```

This is the debug version of the command
```
2019/09/16 10:18:16 [keyring] Considering backends: [pass file]
2019/09/16 10:18:16 [keyring] Failed backend pass: The pass program is not available
2019/09/16 10:18:16 [keyring] Expanded file dir to /home/bangn/.buildkite/keyring/
2019/09/16 10:18:16 [keyring] Expanded file dir to /home/bangn/.buildkite/keyring/
Enter passphrase to unlock /home/user/.buildkite/keyring/:
🚨 Pipeline doesn't exist
```

Im using `bk` cli version `1.0.0` on debian 10.

Do you have any idea on why it cannot `browse` to the pipeline?

Cheers,
Bang

**Comment by mcncl** [comment]
👋 With the release of `3.x.x` we now parse pipeline information differently, so I'm going to close this as unplanned as I don't _think_ it's relevant to the latest release. If that isn't correct then feel free to re-open this with information on how it impacts `3.x.x` 🙂
