### ISSUE TITLE
Infinite builds

### ISSUE THREAD

**Issue by jayco** [buildkite/cli#68]
Hello BK :)

Using the bk init function to set up scaffolding and pushing up the [skeleton init commit](https://github.com/buildkite/cli/blob/c32750a9d45488296abba55dcb122e49532df833/cmd_init.go#L189) results in the agent running infinite builds. 

I used the client to manually init a repo I had to test the bk agent using the AWS stack set up. When I checked the bk pipeline I noticed that it was continually building and had to manually stop the build.

<img width="1206" alt="Screen Shot 2019-10-23 at 7 05 22 am" src="https://user-images.githubusercontent.com/585588/67330158-81d07300-f563-11e9-8e02-4c2e7db77af6.png">

<img width="1172" alt="Screen Shot 2019-10-23 at 7 05 58 am" src="https://user-images.githubusercontent.com/585588/67330230-99a7f700-f563-11e9-9a09-81a0528354b2.png">

I am happy to put in a fix for this - any preferences?

**Comment by mcncl** [comment]
We've recently released v3 and this shouldn't be an issue anymore 🙂 Feel free to reach out if you do face similar issues in the future though
