### ISSUE TITLE
bk gets stuck

### ISSUE THREAD

**Issue by kstenerud** [buildkite/cli#72]
I tried downloading and running the cli for a local build, but it just sat there doing nothing for 10 minutes until I figured it got stuck somehow and hit ^C:

```
karl@chrx:~/work/goprofile_test$ bk local run
>>> Starting local agent 🤖
>>> Starting build 👟
>>> Executing initial command: buildkite-agent pipeline upload
^C
>>> Gracefully shutting down...
🚨 Initial command failed: context canceled
```

When I ran it with debug, it complained about permission problems, and then got stuck again:

```
karl@chrx:~/work/goprofile_test$ bk local run --debug
2019/12/03 13:25:51 [keyring] Considering backends: [pass file]
2019/12/03 13:25:51 [keyring] Failed backend pass: The pass program is not available
2019/12/03 13:25:51 Serving API on http://127.0.0.1:35269
2019/12/03 13:25:51 Creating bootrap script at /tmp/bootstrap-458222797
>>> Starting local agent 🤖
>>> Starting build 👟
>>> Executing initial command: buildkite-agent pipeline upload
open /etc/buildkite-agent/buildkite-agent.cfg: permission denied^C
>>> Gracefully shutting down...

🚨 Initial command failed: context canceled
```

How do I fix this?

**Comment by umanwizard** [comment]
Running as root worked for me.

**Comment by mcncl** [comment]
The `local run` isn't in 3.0.0 and we don't currently have a view to add it in; as has been seen, keeping it in line with the ongoing changes in the agent can mean it falls out of sync. We'll be looking at alternative approaches to using `local run`.
