### ISSUE TITLE
[feature] bk run - allow running local pipeline using remote agents

### ISSUE THREAD

**Issue by drnic** [buildkite/cli#76]
Whilst discovering https://github.com/buildkite/agent/issues/1181 I came across the desire for `bk run` or `bk local run` to split out its behaviour and run a local pipeline, but use remote agents.

I like `bk local run` -- it allows me to test a new pipeline before I "commit" all future PRs/commits/team members to the pipeline changes. You can iterate on the pipeline.

The command happens to run the steps locally; though to me this is tangential.

I can imagine this is not a small PR. I wanted to raise the topic and perhaps someone can contribute if its a good or bad idea.

**Comment by mcncl** [comment]
👋 We don't currently support a `local run` command in the new CLI version (`3.x.x`). As you've seen, there are some complexities around having a `local run` command in the CLI and we're looking at other methods of providing this functionality.
