### ISSUE TITLE
Issue using the junit plugin on osx

### ISSUE THREAD

**Issue by remi-debette** [buildkite/cli#81]
Hi
First, thank you for the great tool which allows to test our pipelines on local.

Running the tool installed from brew on osx, I encountered an issue that seems to be linked with the peculiar status of the platform.

When running the sample pipeline of the plugin: [junit-annotate](https://github.com/buildkite-plugins/junit-annotate-buildkite-plugin ), I see the following error happening:
```bash
 bk local run .buildkite/pipeline.integration_tests.yml
(...)

--- :junit: Processing the junits
docker: Error response from daemon: Mounts denied: 
The path /var/folders/kf/fsdklxv57_v6kq5ydjxpj6g00000gp/T/buildkite-plugins-670558647/github-com-buildkite-plugins-junit-annotate-buildkite-plugin-v1-7-0/ruby
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0000] error waiting for container: context canceled 
🚨 Error: The command exited with status 125

```

Apparently, when trying to mount such a folder on a mac, one would need to prefix `/var` with `/private` and use instead `/private/var` according to [this comment
](https://stackoverflow.com/a/45123074)

Is this a problem of the plugin or of the bk local agent?

**Comment by pzeballos** [comment]
Hey! Sorry for the delay! If you are still having issues, can you send your build details to support@buildkite.com? :pray:  Thanks!

**Comment by mcncl** [comment]
👋 We don't currently support a `local run` command in the new CLI version (`3.x.x`). As you've seen, there are some complexities around having a `local run` command in the CLI and we're looking at other methods of providing this functionality.
