### ISSUE TITLE
FR: Command to set up github webhook

### ISSUE THREAD

**Issue by petemounce** [buildkite/cli#84]
It would be great to be able to run something like `bk setup github webhook --organisation ... --repository ... --pipeline ...` and have a correctly-configured github webhook set up against the pipeline.

Since there's already a github and a buildkite auth token somewhere available after setting up `bk` this sounds quite achieveable.

Would you welcome a PR that adds this, if you don't yourselves do it?

**Comment by mcncl** [comment]
👋 Thanks for this issue! The new version of the CLI doesn't require a GitHub token, and so we can't assume that one is present. We may look in to introducing the functionality in this issue at a later date, however our currently aim is to be agnostic in which VCS is in use.
