### ISSUE TITLE
Emoji with dashes unsupported

### ISSUE THREAD

**Issue by sj26** [buildkite/cli#99]
There's a report in the emojis repo that `:amazon-cogito:` isn't recognised: https://github.com/buildkite/emojis/issues/252

I believe it's because of this emoji regexp:
https://github.com/buildkite/cli/blob/e635a7d96563e6488376a0fe942b48f959f94686/local/emoji.go#L28

`\w` does not include `-` (see [the re2 docs](https://github.com/google/re2/wiki/Syntax)) so it isn't matching.

**Comment by mcncl** [comment]
👋 Thanks for the issue! There isn't currently a `local` command in the newer version (`3.x.x`) of the CLI and so I'm going to move this to closed, unplanned. We're looking at alternative solutions to support local runs that don't require as much maintenance.
